### ISSUE TITLE
Composer install should install latest stable

### ISSUE THREAD

**Issue by hardyjohnson** [copious-cookbooks/composer#8]
Currently we are installing dev branch composer, it will be better to install latest stable version.

**Comment by hardyjohnson** [comment]
Note understood this could be a downstream attribute, so there is a current work around.

**Comment by colby** [comment]
https://getcomposer.org/versions can be helpful in determining latest stable.

**Comment by jerrywardlow** [comment]
Researching the Github API for this one to see if we can easily bypass the official Composer website and find out the latest release

**Comment by hardyjohnson** [comment]
We can do as long as we don't need to verify the shasum which is tied to the getcomposer damn site.

**Comment by jerrywardlow** [comment]
Fixed in #9
